runtime: nodejs20

# App Engine configuration for SIBLO Web Game
instance_class: F1

# Environment variables
env: standard

# Handlers for static assets and routing
handlers:
  # Static assets with long-term caching
  - url: /assets
    static_dir: dist/assets
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  # Favicon and other root static files
  - url: /(.*\.(ico|png|jpg|jpeg|gif|svg|webp))$
    static_files: dist/\1
    upload: dist/.*\.(ico|png|jpg|jpeg|gif|svg|webp)$
    secure: always
    http_headers:
      Cache-Control: "public, max-age=86400"

  # All other routes - SPA fallback to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"